; ============================================================
; ESP32 LoRa 网关 — 华为云 IoT 水情监测
; PlatformIO 项目配置
; ============================================================

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
monitor_filters = direct

; 核心库
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21


; 串口配置
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192

; Flash 配置
board_build.flash_mode   = dio
board_build.f_flash      = 80000000L
board_build.partitions   = default.csv
